---
  - name: Entr
    block:

    - name: Check if entr is installed
      ansible.builtin.shell:
        cmd: which entr
      register: entr_exists
      ignore_errors: true

    - name: Set target dir
      ansible.builtin.set_fact:
        entr_dir: "{{ ansible_user_dir }}/.entr"
      ignore_errors: true

    - name: Entr | Clone Latest Version
      ansible.builtin.git:
        repo: https://github.com/eradman/entr.git
        depth: 1
        dest: "{{ entr_dir }}"
      ignore_errors: true
      when: entr_exists.rc == 0

    - name: Entr | Configure
      ansible.builtin.shell:
        cmd: ./configure
        chdir: "{{ entr_dir }}"
      ignore_errors: true
      when: entr_exists.rc == 0

    - name: Entr | Make test
      ansible.builtin.shell:
        cmd: make test
        chdir: "{{ entr_dir }}"
      ignore_errors: true
      when: entr_exists.rc == 0

    - name: Entr | Make install
      ansible.builtin.shell:
        cmd: make install
        chdir: "{{ entr_dir }}"
      ignore_errors: true
      when: entr_exists.rc == 0

    - name: Entr | Cleanup
      ansible.builtin.shell:
        cmd: rm -rf "{{ entr_dir }}"
      ignore_errors: true
      when: entr_exists.rc == 0