---
# tasks file for sudo-pair

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: true
  delegate_to: localhost
  when: ansible_facts['os_family'] != 'Darwin'

- name: Install requirements for cargo
  ansible.builtin.package:
    name: "{{ cargo_requirements }}"
    state: present
  become: false
  ignore_errors: true
  when: ansible_facts['os_family'] != 'Darwin'

- name: Download installer rustup
  ansible.builtin.get_url:
    url: "https://static.rust-lang.org/rustup.sh"
    dest: "{{ cargo_tmp }}/rustup.sh"
    mode: "750"
    validate_certs: false
  become: false
  ignore_errors: true
  when: ansible_facts['os_family'] != 'Darwin'

- name: Run installer rustup
  ansible.builtin.command:
    cmd: "./rustup.sh -y"
    chdir: "{{ cargo_tmp }}"
    creates: "{{ cargo_prefix }}/bin/cargo"
  environment:
    CARGO_HOME: "{{ cargo_prefix }}"
    TMPDIR: "{{ cargo_tmp }}"
  become: false
  ignore_errors: true
  when: ansible_facts['os_family'] != 'Darwin'
