---
  - name: "Volta | Detect Volta"
    command: which volta
    register: volta_exists
    ignore_errors: true

  - name: "Node | Detect Node"
    command: which node
    register: node_exists
    ignore_errors: true

  - name: "PNPM | Detect PNPM"
    command: which pnpm
    register: pnpm_exists
    ignore_errors: true

  - name: "Volta | Install Volta"
    when: volta_exists.rc != 0
    block:
      - name: "Volta | Download Volta Install Script"
        ansible.builtin.get_url:
          url: https://get.volta.sh
          dest: /{{ ansible_user_dir }}/get_volta.sh
          force: true
          mode: "0755"

      - name: "Volta | Run the install script"
        ansible.builtin.script:
          cmd: /{{ ansible_user_dir }}/get_volta.sh

  - name: Node - Install Node
    when: node_exists.rc != 0
    ansible.builtin.shell:
      cmd: volta install node

  - name: PNPM - Install PNPM
    when: pnpm_exists.rc != 0
    ansible.builtin.shell:
      cmd: volta install node