---
  - name: Check if ripgrep is installed
    ansible.builtin.shell:
      cmd: which rg
    register: ripgrep_exists

  - name: Check if ripgrep is installed
    ansible.builtin.shell:
      cmd: brew install ripgrep
    when: ansible_facts['os_family'] == 'Darwin' and ripgrep_exists.rc == 0

  - name: Check if ripgrep is installed
    ansible.builtin.shell:
      cmd: sudo apt-get install ripgrep
    when: ansible_facts['os_family'] == 'Linux' and ripgrep_exists.rc == 0