---
  - name: Install Homebrew on supported systems
    hosts: all
    become: yes
    gather_facts: yes

    tasks:
      - name: Ensure required packages are installed on Linux
        apt:
          name:
            - build-essential
            - curl
            - file
            - git
          state: present
        when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'RedHat'

      - name: Install Homebrew on macOS
        shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        args:
          executable: /bin/bash
        when: ansible_facts['os_family'] == 'Darwin'

      - name: Install Homebrew on x86_64 Linux
        shell: /usr/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        args:
          executable: /bin/bash
        environment:
          NONINTERACTIVE: "1"
        when: ansible_facts['os_family'] != 'Darwin' and ansible_facts['architecture'] == 'x86_64'

      - name: Add Homebrew to PATH on macOS and Linux
        shell: echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.profile
        args:
          executable: /bin/bash
        when: ansible_facts['os_family'] == 'Darwin' or ansible_facts['architecture'] == 'x86_64'

      - name: Source Homebrew
        shell: /bin/bash -c 'source ~/.profile'
        args:
          executable: /bin/bash
        when: ansible_facts['os_family'] == 'Darwin' or ansible_facts['architecture'] == 'x86_64'
