---
  - name: Check if dust is installed
    ansible.builtin.shell:
      cmd: which dust
    register: dust_exists

  - name: Install dust
    ansible.builtin.shell:
      cmd: brew install dust
    when: dust_exists.rc != 0
    ignore_errors: true