---
- name: Run Ubuntu Tasks
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'
  ignore_errors: yes

- name: Run MacOS Tasks
  ansible.builtin.import_tasks: macos.yml
  when: ansible_os_family == 'Darwin'
  ignore_errors: yes
